[server]
address = "127.0.0.1"
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#58DFC1"
backgroundColor = "#0C1420"
secondaryBackgroundColor = "#142333"
textColor = "#E8F0F5"
font = "sans serif"
